(function(){
  "use strict";
  window.LiftHaulCargoFirst=true;
  var $=function(s){return document.querySelector(s);};
  var all=function(s){return Array.prototype.slice.call(document.querySelectorAll(s));};
  var TAX_RATE=.12;
  var SERVICE={EXPRESS:{name:"Express",multiplier:1.5},STANDARD:{name:"Standard",multiplier:1},ECONOMY:{name:"Economy / Consolidated",multiplier:.85},DEDICATED:{name:"Dedicated",multiplier:1.25},ENGINEERED_HEAVY_HAUL:{name:"Engineered Heavy Haul",multiplier:null}};
  var RATES={moto:[60,8],sedan:[120,14],mpv:[180,18],pickup:[220,22],van:[300,28],refvan:[420,32],"6w":[1200,55],"6wref":[1550,64],"10w":[2500,80],lowbed:[null,null],crane:[null,null],manual:[null,null]};
  var CATALOG=[
    {id:"moto",name:"Motorcycle",payload:30,volume:.06,dims:[40,40,40],body:"cargo carrier",port:false},
    {id:"sedan",name:"Sedan / Hatchback",payload:200,volume:.4,dims:[90,90,50],body:"enclosed",port:false},
    {id:"mpv",name:"MPV / SUV",payload:300,volume:1,dims:[110,100,80],body:"enclosed",port:false},
    {id:"pickup",name:"Pickup Truck",payload:1000,volume:2.5,dims:[180,140,50],body:"open pickup",port:false},
    {id:"van",name:"L300 / Closed Van",payload:1000,volume:5,dims:[250,150,150],body:"closed van",closed:true,port:false},
    {id:"refvan",name:"Light Refrigerated Van",payload:900,volume:4,dims:[250,150,150],body:"refrigerated van",closed:true,refrigerated:true,port:false},
    {id:"6w",name:"6-Wheel Truck",payload:8000,volume:24,dims:[500,210,220],body:"truck body",port:true},
    {id:"6wref",name:"6-Wheel Refrigerated Truck",payload:7000,volume:22,dims:[500,210,220],body:"refrigerated body",closed:true,refrigerated:true,port:true},
    {id:"10w",name:"10-Wheel Wing Van",payload:14000,volume:45,dims:[800,240,250],body:"wing van",closed:true,side:true,port:true},
    {id:"lowbed",name:"Low-Bed Trailer",payload:40000,volume:0,dims:[null,null,null],body:"low-bed",flatbed:true,permit:true,port:true,heavy:true},
    {id:"crane",name:"Crane Truck",payload:10000,volume:0,dims:[null,null,null],body:"lifting vehicle",lifting:true,permit:true,port:false,heavy:true}
  ];
  var state={selected:null,vehicleCount:1,match:null,signature:null,busy:false};
  var scrollMode=function(){return matchMedia&&matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth";};
  var peso=function(n){return "₱"+Number(n||0).toLocaleString("en-PH",{maximumFractionDigits:2});};
  function esc(s){return String(s==null?"":s).replace(/[&<>\"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c];});}
  function apiBase(){var b=(window.RGO_CONFIG&&window.RGO_CONFIG.apiBase)||"";try{b=b||localStorage.getItem("lifthaul_api_base")||localStorage.getItem("rgo_api_base")||"";}catch(_e){}return b.replace(/\/+$/,"");}
  function svgTruck(){return '<svg width="30" height="22" viewBox="0 0 36 24" aria-hidden="true"><path d="M2 5h20v13H2zM22 10h7l5 5v3H22z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="9" cy="20" r="2"/><circle cx="28" cy="20" r="2"/></svg>';}

  function normalizeCargo(){
    var weight=Number($("#cargoWeight").value||0);if($("#weightUnit").value==="T")weight*=1000;
    var factor=$("#dimensionUnit").value==="M"?100:1;
    var L=Number($("#packageLength").value||0)*factor,W=Number($("#packageWidth").value||0)*factor,H=Number($("#packageHeight").value||0)*factor;
    var count=Number($("#packageCount").value||0),volume=(L&&W&&H&&count)?L*W*H*count/1000000:0;
    var handling=all('input[name="specialHandling"]:checked').map(function(x){return x.value;});
    return {weight:weight,L:L,W:W,H:H,count:count,volume:volume,handling:handling,category:$("#cargoCategory").value,
      stackable:$("#stackable").checked,fragile:$("#fragile").checked,splittable:$("#splittable").checked};
  }
  function locationReady(){return ["oIsland","oRegion","oProvince","oCity","oBarangay","dIsland","dRegion","dProvince","dCity","dBarangay","km"].every(function(id){return !!$("#"+id).value;});}
  function signature(){var c=normalizeCargo();return JSON.stringify([c,$("#oIsland").value,$("#dIsland").value,$("#km").value]);}
  function cargoReady(c){return !!(c.category&&c.weight>0&&c.count>0&&c.L>0&&c.W>0&&c.H>0);}
  function updateVolume(){var c=normalizeCargo();$("#cargoVolume").textContent=c.volume?"Estimated total cargo volume: "+c.volume.toFixed(3)+" m³":"Estimated total cargo volume: waiting for complete dimensions";}
  function filterHandling(){var cat=$("#cargoCategory").value;all("#handlingOptions .handling-option").forEach(function(label){var spec=label.getAttribute("data-for")||"GENERAL";label.hidden=!(spec.indexOf("GENERAL")>-1||spec.indexOf(cat)>-1);if(label.hidden)label.querySelector("input").checked=false;});}
  function payloadBase(){
    var c=normalizeCargo(),origin=window.LiftHaulBookingUX?LiftHaulBookingUX.getLocation("o"): {},destination=window.LiftHaulBookingUX?LiftHaulBookingUX.getLocation("d"): {};
    return {origin_island:$("#oIsland").value,dest_island:$("#dIsland").value,origin_location:origin,destination_location:destination,km:$("#km").value,
      cargo_category:c.category,cargo:$("#cargoDesc").value.trim(),package_count:c.count,weight_kg:c.weight,
      package_length_cm:c.L,package_width_cm:c.W,package_height_cm:c.H,cargo_volume_cbm:c.volume,
      declared_value:$("#declaredValue").value||null,special_handling:c.handling,stackable:c.stackable,fragile:c.fragile,splittable:c.splittable};
  }
  function denial(v,c,inter){var reasons=[],safety=.10,required=c.weight*(1+safety);if(v.payload<required)reasons.push("Payload is insufficient after the 10% safety allowance");if(v.volume&&c.volume>v.volume)reasons.push("Cargo volume exceeds the verified body volume");
    if(v.dims[0]&&c.L>v.dims[0])reasons.push("Cargo is too long");if(v.dims[1]&&c.W>v.dims[1])reasons.push("Cargo is too wide");if(v.dims[2]&&c.H>v.dims[2])reasons.push("Cargo is too tall");
    if(inter&&!v.port)reasons.push("Inter-island port eligibility is not configured");if(c.category==="REFRIGERATED_PERISHABLE"&&!v.refrigerated)reasons.push("Refrigeration is required");
    if(c.category==="HAZARDOUS_REGULATED")reasons.push("Hazardous-material authority requires operations review");if(c.category==="MACHINERY_EQUIPMENT"&&!(v.flatbed||v.lifting))reasons.push("Machinery needs flatbed/low-bed or lifting capability");
    var h=c.handling;if((h.indexOf("CLOSED_VAN")>-1||h.indexOf("WEATHER_PROTECTION")>-1)&&!v.closed)reasons.push("A closed/weather-protected body is required");if(h.indexOf("REFRIGERATED")>-1&&!v.refrigerated)reasons.push("Refrigeration is required");
    if((h.indexOf("CRANE_BOOM")>-1||h.indexOf("TOP_LOADING")>-1)&&!(v.lifting||v.flatbed))reasons.push("Verified lifting/top-loading capability is required");if(h.indexOf("FLATBED")>-1&&!v.flatbed)reasons.push("A flatbed or low-bed is required");
    if(h.indexOf("CONTAINER_CHASSIS")>-1)reasons.push("Container chassis requires operations assessment");if(h.indexOf("SIDE_LOADING")>-1&&!(v.side||v.flatbed))reasons.push("Side-loading capability is required");if(h.indexOf("TAIL_LIFT")>-1)reasons.push("Tail-lift capability requires unit-level verification");if(h.indexOf("FORKLIFT_SUPPORT")>-1)reasons.push("Forklift support requires operations confirmation");return reasons;}
  function localRecommendation(){var c=normalizeCargo(),inter=$("#oIsland").value!==$("#dIsland").value,eligible=[],rejected=[];CATALOG.forEach(function(v){var reasons=denial(v,c,inter);if(reasons.length)rejected.push({id:v.id,name:v.name,explanations:reasons});else eligible.push({v:v,units:1});});
    if(!eligible.length&&c.splittable&&c.count>1){CATALOG.forEach(function(v){var clone=Object.assign({},c,{weight:0,volume:0}),reasons=denial(v,clone,inter).filter(function(r){return r.indexOf("Payload")<0&&r.indexOf("volume")<0;});var usable=v.payload/1.1,units=Math.max(Math.ceil(c.weight/usable),v.volume?Math.ceil(c.volume/v.volume):1);if(!reasons.length&&units<=Math.min(c.count,12))eligible.push({v:v,units:units});});}
    var needRef=c.category==="REFRIGERATED_PERISHABLE"||c.handling.indexOf("REFRIGERATED")>-1;eligible.sort(function(a,b){var pa=(needRef===!!a.v.refrigerated?0:1)+(a.v.permit?2:0)+(a.v.lifting?1:0),pb=(needRef===!!b.v.refrigerated?0:1)+(b.v.permit?2:0)+(b.v.lifting?1:0);return a.units-b.units||pa-pb||a.v.payload-b.v.payload;});
    var opts=eligible.slice(0,4).map(function(x,i){return {id:x.v.id,name:x.v.name,classification:i?"ALTERNATIVE":"RECOMMENDED",vehicle_count:x.units,verified_payload_kg:x.v.payload,usable_cargo_weight_kg:Math.round(x.v.payload/1.1),safety_allowance_pct:.10,volume_cbm:x.v.volume,body_dimensions_cm:x.v.dims,body_type:x.v.body,refrigerated:!!x.v.refrigerated,lifting_capable:!!x.v.lifting,special_permit_required:!!x.v.permit,availability:"Verified unit and service-area availability checked before assignment",reason:i?"Safe eligible alternative with additional capacity or specialization.":"Best fit for the entered cargo, route and handling requirements."};});
    return {matching_version:"CARGO_MATCH_V2_DEMO_SNAPSHOT",manual_assessment_required:!opts.length,message:opts.length?"Safety match uses the current administrator-managed category snapshot.":"Your cargo requires a customized transport assessment. Please submit the booking for review by our operations team.",options:opts,rejected:rejected};
  }
  function requestRecommendation(){var c=normalizeCargo(),stage=$("#vehicleStage"),msg=$("#vehicleGateMessage");updateVolume();if(!locationReady()||!cargoReady(c)){state.match=null;state.selected=null;stage.className="booking-step vehicle-stage locked";$("#veh").innerHTML="";msg.className="match-status";msg.textContent="Complete both locations and all required cargo fields to calculate safe vehicle options.";estimate();return Promise.resolve(null);}var sig=signature();msg.textContent="Checking verified capacity, dimensions, route and handling requirements…";stage.className="booking-step vehicle-stage ready";var base=apiBase(),work=base?fetch(base+"/public/bookings/vehicle-recommendations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payloadBase())}).then(function(r){return r.json().then(function(j){if(!r.ok||j.error)throw new Error(j.error||"Vehicle match failed");return j.data;});}):Promise.resolve(localRecommendation());return work.then(function(result){state.match=result;state.signature=sig;renderRecommendations(result);return result;}).catch(function(err){state.match=null;state.selected=null;stage.className="booking-step vehicle-stage locked";msg.className="match-status error";msg.textContent=err.message;$("#veh").innerHTML="";return null;});}
  function renderRecommendations(result){var stage=$("#vehicleStage"),msg=$("#vehicleGateMessage");stage.className="booking-step vehicle-stage "+(result.manual_assessment_required?"manual":"ready");msg.className="match-status";msg.textContent=result.message;if(result.manual_assessment_required){state.selected="manual";state.vehicleCount=0;$("#veh").innerHTML='<button type="button" class="vopt on" data-v="manual"><span class="vtag">Operations review</span><b>Customized transport assessment</b><span class="vreason">No standard category passed every safety gate. The system will not guess or permit an unsafe override.</span></button>';populateLevels(true);}else{$("#veh").innerHTML=result.options.map(function(v){var dims=(v.body_dimensions_cm||[]).every(Boolean)?v.body_dimensions_cm.join(" × ")+" cm":"open/specialized body";return '<button type="button" class="vopt" data-v="'+esc(v.id)+'">'+svgTruck()+'<span class="vtag">'+esc(v.classification)+(v.vehicle_count>1?' · '+v.vehicle_count+' vehicles':'')+'</span><b>'+esc(v.name)+'</b><span>Verified payload '+Number(v.verified_payload_kg).toLocaleString("en-PH")+' kg</span><span class="vmeta">'+esc(dims)+' · '+esc(v.volume_cbm||"open")+' m³</span><span class="vreason">'+esc(v.reason)+'</span></button>';}).join("");chooseVehicle(result.options[0].id,result.options[0].vehicle_count);}
    var rejected=result.rejected||[];$("#rejectedVehicles").hidden=!rejected.length;$("#rejectedVehicleList").innerHTML=rejected.slice(0,8).map(function(r){return '<p><b>'+esc(r.name||r.id)+':</b> '+esc((r.explanations||r.reasons||[]).join(" · "))+'</p>';}).join("");$("#vehicleRecommendation").innerHTML='<b>Safety gate passed</b><span>Only options that satisfy the current deterministic rules are selectable. Unit-level legality and service-area availability are checked again before assignment.</span>';$("#vehicleRecommendation").classList.add("show");estimate();}
  function findOption(id){return state.match&&state.match.options?state.match.options.find(function(v){return v.id===id;}):null;}
  function chooseVehicle(id,count){state.selected=id;state.vehicleCount=count||1;all(".vopt").forEach(function(b){b.classList.toggle("on",b.getAttribute("data-v")===id);});var opt=findOption(id);populateLevels(id==="manual"||!!(opt&&(opt.special_permit_required||opt.lifting_capable||id==="lowbed"||id==="crane")));estimate();}
  function populateLevels(heavy){var s=$("#svcLevel"),codes=heavy?["ENGINEERED_HEAVY_HAUL","DEDICATED"]:["EXPRESS","STANDARD","ECONOMY","DEDICATED"];s.innerHTML=codes.map(function(c){return '<option value="'+c+'">'+SERVICE[c].name+'</option>';}).join("");s.value=heavy?"ENGINEERED_HEAVY_HAUL":"STANDARD";}
  function estimate(){var box=$("#estimate"),rate=RATES[state.selected];if(!state.selected||!rate){box.hidden=true;if(window.LiftHaulBookingUX)LiftHaulBookingUX.updatePaymentAmount(null);return;}if(rate[0]==null){box.hidden=false;box.innerHTML='<div class="quoteonly">Customized assessment required. No price is fabricated; operations will verify equipment, permits and route constraints before presenting an agreed transport-service charge.</div>';if(window.LiftHaulBookingUX)LiftHaulBookingUX.updatePaymentAmount(null);return;}var km=Number($("#km").value||0);if(!km){box.hidden=true;return;}var m=(SERVICE[$("#svcLevel").value]||SERVICE.STANDARD).multiplier||1,units=state.vehicleCount||1,transport=Math.round((rate[0]+rate[1]*km)*m*units),fee=Math.round(transport*.10),transportTax=Math.round(transport*TAX_RATE),feeTax=Math.round(fee*TAX_RATE),tax=transportTax+feeTax,total=transport+fee+tax;box.hidden=false;box.innerHTML='<span class="step-kicker">Step 6 · Price review</span><div class="row"><span>Agreed transport-service charge preview'+(units>1?' · '+units+' vehicles':'')+'</span><span>'+peso(transport)+'</span></div><div class="row fee"><span>Haulift administration fee · 10%</span><span>'+peso(fee)+'</span></div><div class="row"><span>Applicable tax · configured preview</span><span>'+peso(tax)+'</span></div><div class="row total"><span>Total Protected-Payment amount</span><span>'+peso(total)+'</span></div><div class="row"><span>Excluded: tolls, RoRo/ferry, ports, permits and incidentals</span><span>Paid separately</span></div>';if(window.LiftHaulBookingUX)LiftHaulBookingUX.updatePaymentAmount(total);}
  var timer=null;function scheduleMatch(){clearTimeout(timer);timer=setTimeout(requestRecommendation,180);}
  function collectStops(){return all("#stops .stopAddr").map(function(x){return x.value.trim();}).filter(Boolean).map(function(a){return{type:"DROP",address:a};});}
  function showMatch(){$("#bookform").style.display="none";$("#match").classList.add("show");$("#spin").style.display="";$("#newBooking").style.display="none";$("#match").scrollIntoView({behavior:scrollMode(),block:"center"});}
  function finish(ref,title,sub,ii){$("#ref").textContent="Booking "+ref;$("#spin").style.display="none";$("#matchTitle").textContent=title;$("#matchSub").textContent=sub;var stages=ii?["Request Received","Quotation","Payment","Matching","Assigned","Pickup","In Transit","At Port","Sea Leg","Destination Port","Delivered","POD","Settled"]:["Request Received","Quotation","Payment","Matching","Assigned","Pickup","In Transit","Delivered","POD","Settled"];$("#track").innerHTML=stages.map(function(s,i){return '<div class="tstep '+(i===0?'cur':'')+'"><div class="ic">'+(i===0?'●':i+1)+'</div><div><b>'+s+'</b></div></div>';}).join("");$("#newBooking").style.display="";}
  function fail(message){$("#spin").style.display="none";$("#ref").textContent="";$("#track").innerHTML="";$("#matchTitle").textContent="Booking was not saved";$("#matchSub").textContent=message;$("#newBooking").textContent="Return to booking form";$("#newBooking").style.display="";state.busy=false;}
  function fullPayload(){var p=payloadBase(),contact=$("#cContact").value.trim(),origin=p.origin_location,dest=p.destination_location;p.contact_name=$("#cName").value.trim();p.origin_city=origin.full_address||origin.locality_name||$("#oCity").value;p.dest_city=dest.full_address||dest.locality_name||$("#dCity").value;p.vehicle=state.selected;p.vehicle_count=state.vehicleCount;p.matching_version=state.match&&state.match.matching_version;p.payment="protected";p.excluded_charges_ack=$("#excludedAck").checked;p.service_level=$("#svcLevel").value||"STANDARD";p.schedule_type=$("#schedType").value||"NOW";if(p.schedule_type==="SCHEDULED")p.scheduled_at=$("#schedAt").value;p.stops=collectStops();p.cargo_photo_count=$("#cargoPhotos").files.length;p.idempotency_key=(window.crypto&&window.crypto.randomUUID)?window.crypto.randomUUID():"web-"+Date.now();if(contact.indexOf("@")>-1)p.contact_email=contact;else p.contact_phone=contact;return p;}
  function submit(e){e.preventDefault();if(state.busy)return;if(!$("#bookform").reportValidity())return;if(state.signature!==signature()||!state.match){requestRecommendation().then(function(){if(state.match)$("#bookform").requestSubmit();});return;}if(!state.selected){$("#vehicleStage").scrollIntoView({behavior:scrollMode()});return;}if(!$("#excludedAck").checked){$("#excludedAck").focus();return;}var base=apiBase();if(!base){failBefore("Connect the hosted LiftHaul API before submitting. Vehicle matching works in this demo, but no local or fake booking will be created.");return;}state.busy=true;$("#bookbtn").disabled=true;showMatch();var p=fullPayload();fetch(base+"/public/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}).then(function(r){return r.json().then(function(j){if(!r.ok||j.error)throw new Error(j.error||"Booking failed");return j.data;});}).then(function(d){var q=d.quote_breakdown||{},name=state.selected==="manual"?"Operations assessment":((findOption(state.selected)||{}).name||state.selected),sub=d.estimate==null?(d.estimate_note+" "+d.next_step):("Protected-Payment total "+peso(q.total_protected_payment||d.estimate)+" · transport "+peso(q.transport_service_charge)+" + 10% fee "+peso(q.administration_fee)+" + tax "+peso(q.applicable_tax)+". Excluded route expenses remain separate.");finish(d.ref,"Request received · "+name,sub,d.inter_island);if(d.tracking_token)$("#ref").insertAdjacentHTML("afterend",'<a class="btn accent block" style="margin-top:12px" href="track.html?t='+encodeURIComponent(d.tracking_token)+'">Track this booking →</a>');}).catch(function(err){fail(err.message||"No booking was created.");});}
  function failBefore(message){$("#vehicleGateMessage").className="match-status error";$("#vehicleGateMessage").textContent=message;$("#vehicleStage").scrollIntoView({behavior:scrollMode(),block:"center"});}

  var cargo=$("#cargoCard"),distance=$("#distanceMeta");if(cargo&&distance)distance.closest(".field").after(cargo);
  populateLevels(false);filterHandling();updateVolume();
  $("#vehGrid").innerHTML=CATALOG.map(function(v){return '<div class="vcard'+(v.heavy?' heavy':'')+'">'+svgTruck()+'<b>'+esc(v.name)+'</b><div class="cap">Verified category payload '+Number(v.payload).toLocaleString("en-PH")+' kg</div><p>Final eligibility depends on cargo dimensions, volume, handling, route and verified unit availability.</p></div>';}).join("");
  all("#cargoCard input,#cargoCard select,#oLocationCard select,#dLocationCard select").forEach(function(el){el.addEventListener("input",scheduleMatch);el.addEventListener("change",function(){filterHandling();scheduleMatch();});});
  $("#oIsland").addEventListener("change",scheduleMatch);$("#dIsland").addEventListener("change",scheduleMatch);document.addEventListener("lifthaul:distancechange",function(e){var d=e.detail&&e.detail.distance;$("#km").value=d&&d.km?d.km:"";$("#distanceMeta").textContent=d?(d.refined?"Distance recalculated from your refined pins.":"Planning distance calculated automatically; dispatch routing is confirmed separately."):"Complete both locations to calculate distance.";scheduleMatch();});
  $("#svcLevel").addEventListener("change",estimate);$("#schedType").addEventListener("change",function(){$("#schedWrap").style.display=this.value==="SCHEDULED"?"":"none";});
  document.addEventListener("click",function(e){var v=e.target.closest(".vopt");if(v){var opt=findOption(v.dataset.v);chooseVehicle(v.dataset.v,opt?opt.vehicle_count:0);return;}if(e.target.id==="addStop"){var row=document.createElement("div");row.className="stoprow";row.style.cssText="display:flex;gap:8px;margin-bottom:6px";row.innerHTML='<input class="stopAddr" placeholder="Stop address" style="flex:1"><button type="button" class="btn line sm rmStop">×</button>';$("#stops").appendChild(row);}if(e.target.classList.contains("rmStop"))e.target.closest(".stoprow").remove();var w=e.target.closest(".bhead button");if(w){all(".bhead button").forEach(function(b){b.classList.toggle("on",b===w);});$("#schedType").value=w.dataset.when==="later"?"SCHEDULED":"NOW";$("#schedType").dispatchEvent(new Event("change"));}if(e.target.id==="newBooking")location.reload();});
  $("#bookform").addEventListener("submit",submit);$("#yr").textContent=new Date().getFullYear();
})();
